using Microsoft.AspNetCore.Http;

namespace Shared.ApiExceptions
{
    /// <summary>
    /// Base class for custom API exceptions used for standardized error handling and responses.
    /// </summary>
    public abstract class ApiException : Exception
    {
        /// <summary> A URI reference that identifies the problem type. Defaults to a standard MDN reference. </summary>
        public virtual string Type { get; set; } = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/500";

        /// <summary> The HTTP status code generated by the origin server for this occurrence of the problem. </summary>
        public virtual int Status { get; } = StatusCodes.Status500InternalServerError;

        /// <summary> A short, human-readable summary of the problem type. </summary>
        public virtual string Title { get; } = "Internal Server Error";

        /// <summary> Initializes a new instance of the ApiException class with a specific detail message. </summary>
        protected ApiException(string message) : base(message) { }
    }
}